# Generated by Django 5.0 on 2026-01-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='report_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
